### ISSUE TITLE
folders are missing

### ISSUE THREAD

**Issue by iij0** [imatge-upc/vqa-2016#3]
Dear Sir,

I am trying to run your code but these folders are missing.
 
PREPROCESSED_PATH = DATA_PATH + 'preprocessed/'
TOKENIZER_PATH = PREPROCESSED_PATH + 'tokenizer.p'
FEATURES_DIR_PATH = PREPROCESSED_PATH + 'features/'
WEIGHTS_DIR_PATH = '../models/weights/'
RESULTS_DIR_PATH = '../results/'

How can I get these materials? I appreciate if you can help me.

**Comment by issey173** [comment]
Hi @iij0 !

Thanks for using our repo! We published the preprocessed features that you need in our public server. You can find the locations of those files in this issue: #2 

The scripts will create the other directories while training the model, the preprocessed features are all you need to actually be able to run our models.

Don't hessitate to ask anything else!
Regards,
Issey
